config/routes.rb
Rails.application.routes.draw do

    root 'posts#index', :as => :home
   get 'posts/:id' => 'posts#show', :as => :post

   get '/about' => 'about#index', :as => :about

end

app/models/author.rb
class Author < ActiveRecord::Base

has_many :posts

validates_presence_of :author_id, :name

end

app/models/locate.rb
def self.search(search)
  search_condition = "%" + search + "%"
  find(:all, :conditions => ['title LIKE ? OR description LIKE ?', search_condition, search_condition])
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :author

  validates_presence_of :title, :body, :summary

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
    @frontpost = @posts.sort_by{|posts| posts.created_at}
    @firstpost = @frontpost.first
  end

  def show
    @showpost = Post.find(params[:id].to_i)
    
  end

  def search
  @locate = Locate.search params[:search]
  end

  def image

  end


end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.erb
    <div class="col-md-3 col-sm-3">
        <img class="img-thumbnail img-responsive photo"<%= image_tag 'image2.jpg' %></img>
    </div>
    <div class="col-md-9 col-sm-9">
        <p>
             Hi my real name is Zack Taylor. I've been learning astrology for last 20 years. Yeah, that's true. Sometimes I used to think this is all bullshit. But still I love doing more research on this. Do you know why? I don't know. May be I don't know how to pass time other ways. I've predicted the future for Bill Clinton, George Bush and Osama Binladen. Everything happened as I said. I've even predicted the future for me and unfortunately it's not going like that way.. he hee.
        </p>

        <p>
            I don't know how to fill this paragraph more, so, Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
        </p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= yield(:top) %></title>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body id="<%= params[:controller] %>" class="<%= params[:action] %>">

    <div class="container-fluid">

      <div class="jumbotron">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand"<%= link_to 'A Morphin Blog', home_path %></a>
            </div>
            <div>
              <ul class="nav navbar-nav">
              </ul>
              <ul id="nav_top" class="nav navbar-nav pull-right">
                <li><a><%= link_to 'About', about_path %></a></li>
                <li><a><%= link_to 'Search', about_path %></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>

      <div class ="container">
          <div class="row">
        <%= yield %>
          </div>
      </div>
      <div class="container-fluid">
          <hr/>
          <%= yield(:bottom) %>
          <footer class="footer">
            <a class="navbar-brand">Zordon Productions, Copyright 2015. All Rights Reserved.</a>
              <ul class="nav navbar-nav pull-right">
                <li><a href="http://www.toywiz.com/rangerminis.html">Store</a></li>
                <li><a href="http://timelife.com/products/power-rangers-from-mighty-morphin-to-lost-galaxy">DVDS</a></li>
                <li><a href="http://www.letsplaysnes.com/play-mighty-morphin-power-rangers-online/">Video Games</a></li>
                <li><a href="https://www.80stees.com/collections/mighty-morphin-power-rangers">T-Shirts</a></li>
              </ul>
          </div>
        </footer>

  </body>
</html>

app/views/posts/index.html.erb
<% content_for :top do %>
<%= "Rangers!" %>
<% end %>

<div class="col-xs-8">
<div class="post-preview">
  <h2 class="post-title">
    <%= @firstpost.title %>
  </h2>
  <h3 class="post-subtitle">
    <%= @firstpost.summary %>
  </h3>
</a>
<p class="post-meta">Posted by <a><%= link_to("#{@firstpost.author.name}", about_path) %></a></p>
</div>
<hr/>
</div>
<div class="col-xs-4">
  <div class="aside"><%= image_tag('logo2.jpg', size: "40") %></img>
  <h5>Zack Taylor</h5>
    <ul class="list-inline">
    <li class="col-xs-4">Twitter</li>
    <li class="col-xs-4">Facebook</li>
    <li class="col-xs-4">Instagram</li>
  </ul>
</div>
  <div class ="aside_image"><%= image_tag('image2.jpg', size: "40x60") %></div>
    <p class="sub-heading">"Looks like it's time to go to work."</p>
  <p class="filler">Quick-witted and clever, Zack relies on a combination of skill, strength, and agility to win his battles. The original Black Ranger. Whenever he didn't have an arm around Trini or Kimberly, Zack could be found pursuing his attractive, but hard-to-get classmate, Angela. Zack always loved a good joke. </p>
</div>

<% content_for :bottom do %>

<h3 class="headline">MOST POPULAR POSTS</h3>
<div class="row">
  <% @posts.take(4).each do |post| %>
  <div class="col-xs-3">
    <%= link_to image_tag(post.image), post_path(post.id) %>
    <p class="image_text"><%= post.title %></p>
  </div>

  <% end %>

  <% end %>

app/views/posts/show.html.erb
<% content_for :top do %>
<%= @showpost.title %>
<% end %>

<div class="col-md-3 col-sm-3">
    <img class="img-thumbnail img-responsive photo"><%= image_tag(@showpost.image) %></img>

</div>
<div class="col-md-9 col-sm-9">
<div class="post-preview">
  <h2 class="post-title">
    <%= @showpost.title %>
  </h2>
  <h3 class="post-subtitle">
    <%= @showpost.summary %>
  </h3>
</a>
<p class="post-meta">Posted by <a><%= link_to("#{@showpost.author.name}", about_path) %></a></p>
</div>
</div>
<hr/>